### ISSUE TITLE
APK is invalid

### ISSUE THREAD

**Issue by 13-beta2** [HazemAM/instant-screen-off#1]
![image](https://user-images.githubusercontent.com/2017168/30548097-d82aa70e-9c99-11e7-92e6-b48e048998ca.png)
OS 6.0.1

**Comment by HazemAM** [comment]
Thanks for the report, @13-beta2.
I updated the release with a new APK. Can you check if it works now?

**Comment by 13-beta2** [comment]
Hi, thank you. Now it works.
